sudo: required
services:
- docker
env:
  global:
  - VERSION="1.5.2"
  - PY27="cp27-cp27mu"
  - PY35="cp35-cp35m"
  - PY36="cp36-cp36m"
before_install:
- docker pull quay.io/pypa/manylinux1_x86_64
- docker run --name "aaa" quay.io/pypa/manylinux1_x86_64 /bin/sh -c "cd && yum update -y && mkdir /wheelhouse &&
  yum install cyrus-sasl-devel zlib-devel -y &&
  wget https://launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-1.0.18.tar.gz &&
  tar -xvf libmemcached-1.0.18.tar.gz &&
  cd libmemcached-1.0.18 &&
  ./configure &&
  make &&
  make install&& 
  cd ../ &&
  git clone -b ${VERSION} git://github.com/lericson/pylibmc/ && cd pylibmc &&
  /opt/python/${PY27}/bin/pip wheel . -w /wheelhouse &&
  auditwheel repair /wheelhouse/pylibmc-${VERSION}-${PY27}-linux_x86_64.whl -w /wheelhouse &&
  /opt/python/${PY35}/bin/pip wheel . -w /wheelhouse &&
  auditwheel repair /wheelhouse/pylibmc-${VERSION}-${PY35}-linux_x86_64.whl -w /wheelhouse &&
  /opt/python/${PY36}/bin/pip wheel . -w /wheelhouse &&
  auditwheel repair /wheelhouse/pylibmc-${VERSION}-${PY36}-linux_x86_64.whl -w /wheelhouse"
- docker cp aaa:/wheelhouse/pylibmc-${VERSION}-${PY27}-manylinux1_x86_64.whl ./
- docker cp aaa:/wheelhouse/pylibmc-${VERSION}-${PY35}-manylinux1_x86_64.whl ./
- docker cp aaa:/wheelhouse/pylibmc-${VERSION}-${PY36}-manylinux1_x86_64.whl ./
script:
- ls
deploy:
  provider: releases
  api_key:
    secure: uPd6QTlepV/A3e7Z2B2UQaXZNnqmSlYWVr50LBS81tTZeMEC29ItmvXfWKnh/W3WfQa6p2GwLWhZdC3DUWCACzyuLeO6KeQVpoAVZTCLwKw5pz97NMnCBEXw/vKjOHGobsYz3nw2EyXmQ3NMEigcBLJqrFi0bsb6Vgp1KZV8kDnyZTCW+73AdDyMJClUeTVYB/F0VJDDeN9ycNY805GoUWaHh3YTq1w/2cSUH5TH/MsNQPBGnbvPDxPOUhas2Q7I2vfztSQ1VfPp02qCckbtaaGf8z6wyYQRFZfIlCtDR/+RJFghXC/ZGRZqfwsw3kOijcZ3o2hTFJF8ZtT0MrbsZLtuw5T/2LWcR2Pw8u9VA7UMncgyZIlFotIR+0ffz6AD2D35gEnE0u4zruCgUmAn+UY/Q/IA5NEgCBU/hsnN9gzhV08xq+cNV2dNmgs+tWuk+ZbFnoOEWJBnEGz96ZNxvCL5uDo64D2WJcHRDCIW6X807LpUOAgOqSiJAZ2EZpRVhlpMbBQt2wemXrqJOIC5mwVC2BpiCUqG1IuIUkfUzFKFkdbQRgs0a8TMpbrvlgHtPoWIU8mUsdGG0LaVlHfyyTlbM24V6jpXnjDce9HcZC3FZD7r1qEezKn7tzEiCE6pZjojPU/+i9Kmm2a05Op5PmARL0c+Ph33r+0wx/9bdmI=
  file:
    - "pylibmc-${VERSION}-${PY27}-manylinux1_x86_64.whl"
    - "pylibmc-${VERSION}-${PY35}-manylinux1_x86_64.whl"
    - "pylibmc-${VERSION}-${PY36}-manylinux1_x86_64.whl"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: bxm156/pylibmc-manylinux
